module.exports = {
    InternalServerError: 'Internal server error',
    NotInteger: 'Not an integer!',
    InvalidDate: 'Invalid date field!',
    InvalidLogin: 'You are not authorized to login!',
    InvalidQuery: 'Invalid query parameter',
    AuthorizationFailed: 'User not Authorized',
    AuthenticationFailed: 'Failed to authenticate token',
    Prohibited: 'Only Admin has access',
    NotFoundUser: 'This account has not been set up on the platform!',
    InvalidUser: 'User id cannot be a string or empty or null!',
    InvalidFirstname: 'Please enter atleast 3 characters as a first name!',
    InvalidLastname: 'Invalid last name!',
    InvalidFullName: 'Please enter atleast 3 characters as a last name!',
    InvalidEmail: 'Please enter a valid email!',
    InvalidPassword: 'Please enter a valid password!',
    InvalidLogin:'Invalid Username & Password',
    EmptyCountry: 'Invalid country!',
    EmptyState: 'Invalid state!',
    EmptyCity: 'Invalid city!',
    EmailAlreadyExists: 'The email address entered already exists!',
    IncorrectPassword: 'The password entered is incorrect!',
    AccountDeactivate: 'Your account has been deactivated on the platform, Please contact admin for help!',
    OtpTimeOut: 'Otp has timed out, new Otp! sent successfully',
    InvalidOtp: 'Wrong Otp',
    NextDateError: 'Next action date must be greater than today',
    IsAdminError: 'Only Admin can Filter by this',
    TransitionNotAllowed:'transition not Allowed',
    successCode : 1,
    errorCode : 0
};